[platformio]
workspace_dir = .pio.nosync
default_envs = esp32dev

;==================== Common settings for all envs ====================
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
  ;==================== Erase WiFi configuration ====================
;  -D WIFI_ERASE
  ;==================== Power & user input ====================
  -D GPIO_PIN_LATCH=25
  -D GPIO_PIN_SWITCH=33

  ;==================== e-Paper display 1.54" 200x200 V1 or V2 ========
  -D E_PAPER_VERSION=2    ; Use 1 or 2, depending on your display version.
  -D E_PAPER_ROTATION=0   ; 0, 1, 2 or 3, depending on your display orientation

  ;==================== Battery measurement ====================
  -D GPIO_PIN_BAT_ADC=34

  ;==================== SPS30 air quality sensor ====================
  -D GPIO_PIN_SPS30_SDA=21
  -D GPIO_PIN_SPS30_SCL=22

  ;==================== PMS5003 air quality sensor ====================
  -D GPIO_PIN_UART_TX2_PMS5003=17    ; to PMS5003 RX pin
  -D GPIO_PIN_UART_RX2_PMS5003=16    ; to PMS5003 TX pin
  -D GPIO_PIN_PMS5003_SET=4
  -D GPIO_PIN_PMS5003_RESET=2

  ;==================== E-paper display (SPI) ====================
  -D GPIO_PIN_EPD_MOSI=23
  -D GPIO_PIN_EPD_MISO=-1
  -D GPIO_PIN_EPD_SCK=18
  -D GPIO_PIN_EPD_CS=27
  -D GPIO_PIN_EPD_DC=19
  -D GPIO_PIN_EPD_RST=13
  -D GPIO_PIN_EPD_BUSY=32

  ;==================== User feedback ====================
  -D GPIO_PIN_LED=2
  -D GPIO_PIN_BUZZER_PWM=14

  ;==================== Application configuration ====================
  -D WARMUP_SECONDS=15
  -D MAX_METINGEN=10

  ;==================== ADC calibration ====================
  -D ADC_VREF_VOLTAGE=3.30f

  ;==================== Battery calibration ====================
  -D BAT_CAL_GAIN=0.94245f
  -D BAT_CAL_OFFSET=0.48763f

  ;==================== Library configuration ====================
  -D DISABLE_DIAGNOSTIC_OUTPUT
  -D CORE_DEBUG_LEVEL=0

lib_deps =
  zinggjm/GxEPD2@^1.6.5
  adafruit/Adafruit GFX Library@^1.11.9
  adafruit/Adafruit BMP280 Library
  adafruit/Adafruit Unified Sensor
  sensirion/Sensirion Core @ ^0.7.2
  sensirion/sensirion-sps
  tzapu/WiFiManager @ ^2.0.17
  https://github.com/mrWheel/safeTimers.git

;==================== OTA upload choice ====================
; Use this environment when uploading over WiFi/OTA.
[env:esp32dev_ota]
extends = env:esp32dev
upload_protocol = espota

; Set this to the OTA hostname that the device reports on screen.
; Example: HHPMS-A1B2C3.local
upload_port = HHPMS-25790C.local
;--upload_port = 192.168.12.42

; Optional OTA password (if configured in code)
; upload_flags =
;   --auth=your-ota-password

